name: GitHub Snake Game

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: LucsBarreto
          outputs: |
            dist/github-snake.svg?color_snake=#00ffcc&color_dots=#000000,#0a192f,#112240,#1f6feb,#58a6ff
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=#00ffcc&color_dots=#000000,#0a192f,#112240,#1f6feb,#58a6ff

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: output
